version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        environment: 
            - logger.level=DEBUG
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1401:1433
        environment:
            SA_PASSWORD: "_Password**98"
            ACCEPT_EULA: "Y"